#=================================================
# Copyright 2025 NTT Corporation
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#=================================================

TOP := vec_fp_inc
VSRC := src/$(TOP).cpp
CFG := $(TOP).cfg

WRAPPER_PARAMS := --IPORT_NUM=1 --OPORT_NUM=1 --OPORT_HEADER_UPDATE="8'd0"

include ../template/makefile.inc
