#=================================================
# Copyright 2025 NTT Corporation
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#=================================================

.PHONY: toe_wrapper

all: toe_wrapper

toe_wrapper:
	@make -C toe_wrapper

clean:
	@make -C toe_wrapper clean
